export const EMPLOYEE_PROFILE_REQUEST = 'EMPLOYEE_PROFILE_REQUEST'
export const EMPLOYEE_PROFILE_SUCCESS = 'EMPLOYEE_PROFILE_SUCCESS'
export const EMPLOYEE_PROFILE_FAIL = 'EMPLOYEE_PROFILE_FAIL'
export const EMPLOYEE_PROFILE_RESET = 'EMPLOYEE_PROFILE_RESET'

export const EMPLOYEE_PROFILE_CREATE_REQUEST = 'EMPLOYEE_PROFILE_CREATE_REQUEST'
export const EMPLOYEE_PROFILE_CREATE_SUCCESS = 'EMPLOYEE_PROFILE_CREATE_SUCCESS'
export const EMPLOYEE_PROFILE_CREATE_FAIL = 'EMPLOYEE_PROFILE_CREATE_FAIL'
export const EMPLOYEE_PROFILE_CREATE_RESET = 'EMPLOYEE_PROFILE_CREATE_RESET'

export const EMPLOYEE_PROFILE_EDIT_REQUEST = 'EMPLOYEE_PROFILE_EDIT_REQUEST'
export const EMPLOYEE_PROFILE_EDIT_SUCCESS = 'EMPLOYEE_PROFILE_EDIT_SUCCESS'
export const EMPLOYEE_PROFILE_EDIT_FAIL = 'EMPLOYEE_PROFILE_EDIT_FAIL'
export const EMPLOYEE_PROFILE_EDIT_RESET = 'EMPLOYEE_PROFILE_EDIT_RESET'

export const EMPLOYEE_ADD_EX_REQUEST = 'EMPLOYEE_ADD_EX_REQUEST'
export const EMPLOYEE_ADD_EX_SUCCESS = 'EMPLOYEE_ADD_EX_SUCCESS'
export const EMPLOYEE_ADD_EX_FAIL = 'EMPLOYEE_ADD_EX_FAIL'
