export const ALL_SCHEDULES_LIST_REQUEST = 'ALL_SCHEDULES_LIST_REQUEST';
export const ALL_SCHEDULES_LIST_SUCCESS = 'ALL_SCHEDULES_LIST_SUCCESS';
export const ALL_SCHEDULES_LIST_FAIL = 'ALL_SCHEDULES_LIST_FAIL';

export const PICK_A_SCHEDULE_REQUEST = 'PICK_A_SCHEDULE_REQUEST';
export const PICK_A_SCHEDULE_SUCCESS = 'PICK_A_SCHEDULE_SUCCESS';
export const PICK_A_SCHEDULE_FAIL = 'PICK_A_SCHEDULE_FAIL';
export const PICK_A_SCHEDULE_RESET = 'PICK_A_SCHEDULE_RESET';
