export const ALL_SCHEDULES_LIST_REQUEST = 'ALL_SCHEDULES_LIST_REQUEST';
export const ALL_SCHEDULES_LIST_SUCCESS = 'ALL_SCHEDULES_LIST_SUCCESS';
export const ALL_SCHEDULES_LIST_FAIL = 'ALL_SCHEDULES_LIST_FAIL';
