export const ALL_SCHEDULES_LIST_REQUEST = 'ALL_SCHEDULES_LIST_REQUEST';
export const ALL_SCHEDULES_LIST_SUCCESS = 'ALL_SCHEDULES_LIST_SUCCESS';
export const ALL_SCHEDULES_LIST_FAIL = 'ALL_SCHEDULES_LIST_FAIL';

export const PICK_A_SCHEDULE_REQUEST = 'PICK_A_SCHEDULE_REQUEST';
export const PICK_A_SCHEDULE_SUCCESS = 'PICK_A_SCHEDULE_SUCCESS';
export const PICK_A_SCHEDULE_FAIL = 'PICK_A_SCHEDULE_FAIL';
export const PICK_A_SCHEDULE_RESET = 'PICK_A_SCHEDULE_RESET';

export const SCHEDULES_LIST_MY_REQUEST = 'SCHEDULES_LIST_MY_REQUEST';
export const SCHEDULES_LIST_MY_SUCCESS = 'SCHEDULES_LIST_MY_SUCCESS';
export const SCHEDULES_LIST_MY_FAIL = 'SCHEDULES_LIST_MY_FAIL';
export const SCHEDULES_LIST_MY_RESET = 'SCHEDULES_LIST_MY_RESET';

export const UNPICK_A_SCHEDULE_REQUEST = 'UNPICK_A_SCHEDULE_REQUEST';
export const UNPICK_A_SCHEDULE_SUCCESS = 'UNPICK_A_SCHEDULE_SUCCESS';
export const UNPICK_A_SCHEDULE_FAIL = 'UNPICK_A_SCHEDULE_FAIL';
export const UNPICK_A_SCHEDULE_RESET = 'UNPICK_A_SCHEDULE_RESET';

export const COMPLETE_SCHEDULE_REQUEST = 'COMPLETE_SCHEDULE_REQUEST';
export const COMPLETE_SCHEDULE_SUCCESS = 'COMPLETE_SCHEDULE_SUCCESS';
export const COMPLETE_SCHEDULE_FAIL = 'COMPLETE_SCHEDULE_FAIL';
export const COMPLETE_SCHEDULE_RESET = 'COMPLETE_SCHEDULE_RESET';

export const ALL_COMPLETED_SCHEDULES_BY_EMP_REQUEST =
  'ALL_COMPLETED_SCHEDULES_BY_EMP_REQUEST';
export const ALL_COMPLETED_SCHEDULES_BY_EMP_SUCCESS =
  'ALL_COMPLETED_SCHEDULES_BY_EMP_SUCCESS';
export const ALL_COMPLETED_SCHEDULES_BY_EMP_FAIL =
  'ALL_COMPLETED_SCHEDULES_BY_EMP_FAIL';
